// <auto-generated />
using LojaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("LojaAPI.Models.Categoria", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nome = "Computadores"
                        },
                        new
                        {
                            id = 2,
                            nome = "Celulares"
                        },
                        new
                        {
                            id = 3,
                            nome = "Eletrodomésticos"
                        });
                });

            modelBuilder.Entity("LojaAPI.Models.Produto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("idCategoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("imagem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("preco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("idCategoria");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            id = 1,
                            idCategoria = 1,
                            imagem = "",
                            nome = "Dell",
                            preco = "3000"
                        },
                        new
                        {
                            id = 2,
                            idCategoria = 1,
                            imagem = "",
                            nome = "Acer",
                            preco = "2500"
                        },
                        new
                        {
                            id = 3,
                            idCategoria = 2,
                            imagem = "",
                            nome = "Motorola",
                            preco = "1500"
                        },
                        new
                        {
                            id = 4,
                            idCategoria = 2,
                            imagem = "",
                            nome = "Apple",
                            preco = "10000"
                        },
                        new
                        {
                            id = 5,
                            idCategoria = 3,
                            imagem = "",
                            nome = "AirFryer",
                            preco = "500"
                        });
                });

            modelBuilder.Entity("LojaAPI.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nome = "Bernardo",
                            senha = "batata"
                        });
                });

            modelBuilder.Entity("LojaAPI.Models.Produto", b =>
                {
                    b.HasOne("LojaAPI.Models.Categoria", "categoria")
                        .WithMany("produtos")
                        .HasForeignKey("idCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");
                });

            modelBuilder.Entity("LojaAPI.Models.Categoria", b =>
                {
                    b.Navigation("produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
